inputs:
  path:
    description: The path to check for non-existence.
    required: true
  match-method:
    description: The method to use for matching the path.
    required: false
    default: exact
    options:
      - exact
      - glob
  message:
    description: An optional message to display on failure.
    type: string
    default: ""

name: Assert Path Not Exists
description: Asserts that a specified path does not exist. Fails the job if it does.
runs:
  using: node24
  main: '../dist/assert-path-not-exists/main/index.js'
