name: Initialize Integration Test
description: Sets up the environment for running integration tests.

runs:
  using: composite
  steps:
    - name: Download dist
      if: ${{ env.SKIP_DIST != 'true' && !env.ACT }}
      uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
      with:
        name: dist
        path: dist/
